from __future__ import annotations

from pathlib import Path
import shutil
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = ROOT / "paper_appendix"
TABLE_DIR = OUT_DIR / "tables"
FIG_DIR = OUT_DIR / "figures"

PMC_DIR = ROOT / "data" / "output" / "paper_model_comparison"
PMC_FIG_DIR = PMC_DIR / "figures"
DIAG_DIR = ROOT / "data" / "diagnostics"
OUT_DATA_DIR = ROOT / "data" / "output"
MIN_YEAR = 2017


def _format_df(df: pd.DataFrame, max_rows: int | None = None) -> pd.DataFrame:
    out = df.copy()

    # Keep appendix tables aligned with analysis sample (2017+).
    if "year" in out.columns:
        out["year"] = pd.to_numeric(out["year"], errors="coerce")
        out = out[out["year"] >= MIN_YEAR]
    elif "date" in out.columns:
        dt = pd.to_datetime(out["date"], errors="coerce")
        out = out[dt.dt.year >= MIN_YEAR]

    if max_rows is not None and len(out) > max_rows:
        out = out.head(max_rows)

    for col in out.columns:
        if pd.api.types.is_float_dtype(out[col]):
            out[col] = out[col].round(4)
    return out


def write_table(csv_path: Path, tex_name: str, caption: str, label: str, max_rows: int | None = None) -> None:
    df = pd.read_csv(csv_path)
    df = _format_df(df, max_rows=max_rows)

    latex = df.to_latex(index=False, escape=True, longtable=False)

    content = (
        "\\begin{table}[htbp]\n"
        "\\centering\n"
        "\\scriptsize\n"
        "\\setlength{\\tabcolsep}{4pt}\n"
        f"\\caption{{{caption}}}\n"
        f"\\label{{{label}}}\n"
        "\\resizebox{\\textwidth}{!}{%\n"
        f"{latex}"
        "}\n"
        "\\end{table}\n"
    )

    (TABLE_DIR / tex_name).write_text(content, encoding="utf-8")


def write_figure_block(src_png: Path, out_name: str, caption: str, label: str) -> None:
    dst_png = FIG_DIR / src_png.name
    shutil.copy2(src_png, dst_png)

    rel_from_root = f"paper_appendix/figures/{src_png.name}".replace('\\\\', '/')
    rel_from_main = f"figures/{src_png.name}".replace('\\\\', '/')
    tex = (
        "\\begin{figure}[htbp]\n"
        "\\centering\n"
        f"\\IfFileExists{{{rel_from_root}}}{{\\includegraphics[width=0.85\\linewidth]{{{rel_from_root}}}}}{{\\includegraphics[width=0.85\\linewidth]{{{rel_from_main}}}}}\n"
        f"\\caption{{{caption}}}\n"
        f"\\label{{{label}}}\n"
        "\\end{figure}\n"
    )
    (FIG_DIR / out_name).write_text(tex, encoding="utf-8")


def write_master_include() -> None:
    lines = [
        "% Auto-generated appendix include file.\n",
        "% Add in your main paper preamble: \\usepackage{float}, \\usepackage{graphicx}, \\usepackage{booktabs}\n",
        "% Then include with: \\input{paper_appendix/appendix_include}\n",
        "\\section{Reproducibility and Implementation Details}\n",
        "This appendix provides reproducibility details, additional diagnostics, and full model-comparison results generated by the code pipeline.\n",
        "\\subsection{Simulation and Numerical Controls}\n",
        "Across Monte Carlo engines, the following implementation controls are used: daily variance cap $\\sigma_t^2 \\le 0.0025$, spread cap of 0.5 (5000 bps), and horizon mapping to 1y/3y/5y ($252/756/1260$ trading days). Antithetic variates are supported and enabled in selected production runs.\n",
        f"All appendix tables based on dated outputs are restricted to {MIN_YEAR}+ observations.\n",
        "\\subsection{Data and Volatility Diagnostics}\n",
        "\\input{paper_appendix/tables/diag_summary}\n",
        "\\input{paper_appendix/tables/garch_param_overall}\n",
        "\\input{paper_appendix/tables/garch_param_breaks}\n",
        "\\subsection{Full Model-Comparison Tables}\n",
        "\\input{paper_appendix/tables/performance_overall}\n",
        "\\input{paper_appendix/tables/performance_by_leverage}\n",
        "\\input{paper_appendix/tables/dm_tests_overall}\n",
        "\\input{paper_appendix/tables/hw_tests_overall}\n",
        "\\input{paper_appendix/tables/msgarch_best_segments_top15}\n",
        "\\subsection{Supplementary Figures}\n",
        "\\input{paper_appendix/figures/rmse_trend_by_year}\n",
        "\\input{paper_appendix/figures/correlation_by_model_maturity}\n",
        "\\input{paper_appendix/figures/firm_rmse_boxplot}\n",
        "\\input{paper_appendix/figures/msgarch_win_share_period_volatility}\n",
    ]
    (OUT_DIR / "appendix_include.tex").write_text("".join(lines), encoding="utf-8")


def write_readme() -> None:
    content = """# Appendix Assets

Generated files for direct inclusion into your LaTeX paper.

## Build

```powershell
\"c:/Users/Chase/Downloads/Seminar QF/.venv/Scripts/python.exe\" paper_appendix/build_appendix_assets.py
```

## Use in paper

1. Ensure your preamble includes:

```latex
\\usepackage{float}
\\usepackage{booktabs}
\\usepackage{graphicx}
```

2. At the appendix location in your main `.tex`:

```latex
\\input{paper_appendix/appendix_include}
```

3. In Overleaf, upload the full `paper_appendix/` folder (including `figures/*.png`).

## Generated outputs

- `paper_appendix/appendix_include.tex`
- `paper_appendix/tables/*.tex`
- `paper_appendix/figures/*.tex` and copied figure PNGs
"""
    (OUT_DIR / "README.md").write_text(content, encoding="utf-8")


def main() -> None:
    TABLE_DIR.mkdir(parents=True, exist_ok=True)
    FIG_DIR.mkdir(parents=True, exist_ok=True)

    # Diagnostics tables
    write_table(
        DIAG_DIR / "garch_param_overall_summary.csv",
        "garch_param_overall.tex",
        "Overall GARCH parameter diagnostics summary.",
        "tab:garch_param_overall",
    )
    write_table(
        DIAG_DIR / "garch_param_break_summary.csv",
        "garch_param_breaks.tex",
        "Break diagnostics for GARCH parameter stability.",
        "tab:garch_param_breaks",
    )

    # Compact diagnostics summary from text report to table
    diag_summary = pd.DataFrame(
        {
            "Metric": ["Total firms", "Problematic firms", "Clean firms"],
            "Value": [34, 25, 9],
        }
    )
    diag_summary.to_latex(
        TABLE_DIR / "diag_summary_body.tex",
        index=False,
        escape=True,
    )
    diag_table = (
        "\\begin{table}[htbp]\n"
        "\\centering\n"
        "\\small\n"
        "\\caption{Volatility diagnostics sample summary.}\n"
        "\\label{tab:diag_summary}\n"
        + (TABLE_DIR / "diag_summary_body.tex").read_text(encoding="utf-8")
        + "\\end{table}\n"
    )
    (TABLE_DIR / "diag_summary.tex").write_text(diag_table, encoding="utf-8")

    # Paper model comparison tables
    write_table(
        PMC_DIR / "performance_overall.csv",
        "performance_overall.tex",
        "Overall model performance by maturity.",
        "tab:perf_overall",
    )
    write_table(
        PMC_DIR / "performance_by_leverage.csv",
        "performance_by_leverage.tex",
        "Model performance by leverage segment.",
        "tab:perf_leverage",
    )
    write_table(
        PMC_DIR / "dm_tests_overall.csv",
        "dm_tests_overall.tex",
        "Diebold-Mariano tests (overall).",
        "tab:dm_overall",
    )
    write_table(
        PMC_DIR / "hw_tests_overall.csv",
        "hw_tests_overall.tex",
        "Hotelling-Williams tests (overall).",
        "tab:hw_overall",
    )
    write_table(
        PMC_DIR / "msgarch_best_segments.csv",
        "msgarch_best_segments_top15.tex",
        "Top 15 segments where MS-GARCH has the highest win share.",
        "tab:msgarch_best_segments",
        max_rows=15,
    )

    # Figure blocks
    write_figure_block(
        PMC_FIG_DIR / "rmse_trend_by_year.png",
        "rmse_trend_by_year.tex",
        "RMSE trend by year across model specifications.",
        "fig:app_rmse_trend",
    )
    write_figure_block(
        PMC_FIG_DIR / "correlation_by_model_maturity.png",
        "correlation_by_model_maturity.tex",
        "Correlation between model-implied and market spread changes by maturity.",
        "fig:app_corr_by_maturity",
    )
    write_figure_block(
        PMC_FIG_DIR / "firm_rmse_boxplot.png",
        "firm_rmse_boxplot.tex",
        "Distribution of firm-level RMSE by model.",
        "fig:app_firm_rmse_boxplot",
    )
    write_figure_block(
        PMC_FIG_DIR / "msgarch_win_share_period_volatility.png",
        "msgarch_win_share_period_volatility.tex",
        "MS-GARCH win share by period and volatility regime.",
        "fig:app_msgarch_win_share",
    )

    write_master_include()
    write_readme()

    # Cleanup helper file not needed in final output
    helper = TABLE_DIR / "diag_summary_body.tex"
    if helper.exists():
        helper.unlink()

    print("Appendix assets generated in:", OUT_DIR)


if __name__ == "__main__":
    main()
